
import java.awt.List;
import java.util.Collection;
import java.util.Collections;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author godoy
 */
public class ApexLegends extends javax.swing.JFrame {

    private DefaultComboBoxModel listaPersonajes = new DefaultComboBoxModel();
    private DefaultComboBoxModel listaJugadores = new DefaultComboBoxModel();
    private Armas arma;

    /**
     * Creates new form ApexLegends
     */
    public ApexLegends() {
        initComponents();
        try {
            this.listaPersonajes.addElement(new Medico("LifeLine", 100, 50, new Armas("Flatline", 10, 80)));
            this.listaPersonajes.addElement(new Rastreador("Vantage", 100, 50, new Armas("PeaceFinder", 30, 40)));
            this.listaPersonajes.addElement(new Fortaleza("Gibby", 125, 75, new Armas("Carabina", 15, 90)));

        } catch (Exception e) {
        }

        jListaPersonajes.setModel(this.listaPersonajes);

        listaJugadores.addElement(new Jugadores("Lechuga", 543, "contraseña", darPersonaje()));
        listaJugadores.addElement(new Jugadores("Loco Bryan", 23, "contraseña", darPersonaje()));
        listaJugadores.addElement(new Jugadores("Dr.Nuila", 2, "contraseña", darPersonaje()));
    }

    public DefaultComboBoxModel getListaPersonajes() {
        return listaPersonajes;
    }

    public void setListaPersonajes(DefaultComboBoxModel listaPersonajes) {
        this.listaPersonajes = listaPersonajes;
    }

    public DefaultComboBoxModel getListaJugadores() {
        return listaJugadores;
    }

    public void setListaJugadores(DefaultComboBoxModel listaJugadores) {
        this.listaJugadores = listaJugadores;
    }

    public Personaje darPersonaje() {
        Random rnd = new Random();
        return (Personaje) listaPersonajes.getElementAt(rnd.nextInt(3));
    }

    public void crearPersonajes() {
        for (int i = 1; i < 57; i++) {
            listaJugadores.addElement(new Jugadores(usuarioRandom(), idGenerator(), usuarioRandom(), darPersonaje()));
        }
    }

    public String usuarioRandom() {
        Random rnd = new Random();
        int repetir = 5;
        String usuario = "";

        while (repetir >= 0) {
            int numRandom = rnd.nextInt(122 - 97 + 1) + 97;

            char caracter = (char) numRandom;
            usuario += caracter;
            repetir--;
        }

        return usuario;
    }

    public int idGenerator() {
        Random rnd = new Random();
        int id = rnd.nextInt(1000);
        boolean centinela = false;
        while (centinela == true) {
            int cont = 0;
            for (int i = 0; i < listaJugadores.getSize(); i++) {
                if (listaJugadores.getElementAt(i) instanceof Jugadores) {
                    if (((Jugadores) listaJugadores.getElementAt(i)).getID() == id) {
                        cont++;
                    }
                }
            }
            if (cont > 0) {
                id = rnd.nextInt();
            } else {
                centinela = true;
            }
        }
        return id;
    }

    public int busquedaBinaria(int numAtacar, int mitad) {
        for (int i = 0; i < listaJugadores.getSize(); i++) {
            if (((Jugadores) listaJugadores.getElementAt(i)).getID() == numAtacar) {
                return listaJugadores.getIndexOf(i);
            } else {

            }
        }
        return 1;
    }

    public void ordenarCombobox() {
        int maximo=0;
        for (int i = 0; i < listaJugadores.getSize(); i++) {
            int max = ((Jugadores) listaJugadores.getElementAt(0)).getID();
            maximo = Math.max(((Jugadores)listaJugadores.getElementAt(i)).getID(),max);
            
        }
        for (int i = 0; i < listaJugadores.getSize(); i++) {
            ((Jugadores) listaJugadores.getElementAt(i)).getID();
        }
    }
    
    public int sinRecursiva(int numId){
        for (int i = 0; i < listaJugadores.getSize(); i++) {
            if (((Jugadores)listaJugadores.getElementAt(i)).getID() == numId) {
                return listaJugadores.getIndexOf(i);
               
            }
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jListaPersonajes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jRestantesTittle = new javax.swing.JLabel();
        jAttackField = new javax.swing.JTextField();
        jAtttackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jJugadoresTabla = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNombreJugador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jArma = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCrearPersonaje_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNombreInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCrearArma_Button = new javax.swing.JButton();
        jPrecision = new javax.swing.JFormattedTextField();
        jFortaleza = new javax.swing.JComboBox<>();
        jVidaPersonaje = new javax.swing.JFormattedTextField();
        jDamageInput = new javax.swing.JFormattedTextField();
        jEscudoPersonaje = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar Personaje");

        jListaPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jListaPersonajes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jListaPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Seleccionar", jPanel1);

        jButton2.setText("Comenzar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRestantesTittle.setText("Restantes: ");

        jAttackField.setText("jTextField1");

        jAtttackButton.setText("Atacar");
        jAtttackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAtttackButtonMouseClicked(evt);
            }
        });

        jJugadoresTabla.setColumns(20);
        jJugadoresTabla.setRows(5);
        jScrollPane2.setViewportView(jJugadoresTabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRestantesTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jAttackField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jAtttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(255, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRestantesTittle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAttackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAtttackButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugar", jPanel2);

        jLabel3.setText("Nombre");

        jLabel4.setText("Vida");

        jLabel5.setText("Fortaleza");

        jLabel6.setText("Escudo");

        jArma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FlatLine", "PeaceFinder", "Carabina" }));

        jLabel7.setText("Arma");

        jCrearPersonaje_Button.setText("Crear Personaje");
        jCrearPersonaje_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCrearPersonaje_ButtonMouseClicked(evt);
            }
        });
        jCrearPersonaje_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearPersonaje_ButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Crear Arma");

        jLabel9.setText("Nombre");

        jLabel10.setText("Daño");

        jLabel11.setText("Precision");

        jCrearArma_Button.setText("Crear Arma");
        jCrearArma_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCrearArma_ButtonMouseClicked(evt);
            }
        });
        jCrearArma_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearArma_ButtonActionPerformed(evt);
            }
        });

        jPrecision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jFortaleza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fortaleza", "Medico", "Rastreador" }));
        jFortaleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFortalezaActionPerformed(evt);
            }
        });

        jVidaPersonaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jDamageInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jDamageInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDamageInputMouseClicked(evt);
            }
        });

        jEscudoPersonaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jEscudoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jVidaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jDamageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jCrearArma_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jArma, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(127, 127, 127)
                                        .addComponent(jPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCrearPersonaje_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jFortaleza, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFortaleza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jVidaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCrearPersonaje_Button)
                    .addComponent(jEscudoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCrearArma_Button)
                    .addComponent(jDamageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCrearPersonaje_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearPersonaje_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrearPersonaje_ButtonActionPerformed

    private void jCrearArma_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearArma_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrearArma_ButtonActionPerformed

    private void jFortalezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFortalezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFortalezaActionPerformed

    private void jCrearArma_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCrearArma_ButtonMouseClicked
        //Agregar un arma
        try {
            String nombre = jNombreInput.getText();
            int damage = Integer.parseInt(jDamageInput.getText());
            int precision = Integer.parseInt(jPrecision.getText());
            this.arma = new Armas(nombre, damage, precision);
            JOptionPane.showMessageDialog(this, "Arma Creada");
            jDamageInput.setText("");
            jPrecision.setText("");
            jNombreInput.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal");

        }


    }//GEN-LAST:event_jCrearArma_ButtonMouseClicked

    private void jDamageInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDamageInputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDamageInputMouseClicked

    private void jCrearPersonaje_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCrearPersonaje_ButtonMouseClicked
        try {
            if (!arma.getNombre().equalsIgnoreCase(null)) {

                String nombre = jNombreJugador.getText();
                int vida = Integer.parseInt(jVidaPersonaje.getText());
                int escudo = Integer.parseInt(jVidaPersonaje.getText());
                int fortaleza = jFortaleza.getSelectedIndex();
                JOptionPane.showMessageDialog(this, fortaleza);
                switch (fortaleza) {
                    case 0:
                        listaPersonajes.addElement(new Fortaleza(nombre, vida, escudo, arma));
                        JOptionPane.showMessageDialog(this, "Personaje Creado");
                        jListaPersonajes.setModel(listaPersonajes);
                        break;
                    case 1:
                        listaPersonajes.addElement(new Medico(nombre, vida, escudo, arma));
                        JOptionPane.showMessageDialog(this, "Personaje Creado");
                        jListaPersonajes.setModel(listaPersonajes);
                        break;
                    case 2:
                        listaPersonajes.addElement(new Rastreador(nombre, vida, escudo, arma));
                        JOptionPane.showMessageDialog(this, "Personaje Creado");
                        jListaPersonajes.setModel(listaPersonajes);
                        break;
                    default:
                        break;
                }
                jNombreJugador.setText("");
                jVidaPersonaje.setText("");
                jEscudoPersonaje.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un arma primero");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }//GEN-LAST:event_jCrearPersonaje_ButtonMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        crearPersonajes();
        jRestantesTittle.setText(String.format("Restantes: %s", listaJugadores.getSize()));
        String message = "";
        for (int i = 0; i < listaJugadores.getSize(); i++) {
            message += String.format("%s%n", listaJugadores.getElementAt(i));
        }
        jJugadoresTabla.setText(message);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jAtttackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAtttackButtonMouseClicked
        int numID = Integer.parseInt(jAttackField.getText());
        if (sinRecursiva(numID)==-1) {
            JOptionPane.showMessageDialog(this, "No existe al que quiere atacar");
        } else {
            
        }
        
    }//GEN-LAST:event_jAtttackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApexLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApexLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApexLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApexLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApexLegends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jArma;
    private javax.swing.JTextField jAttackField;
    private javax.swing.JButton jAtttackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCrearArma_Button;
    private javax.swing.JButton jCrearPersonaje_Button;
    private javax.swing.JFormattedTextField jDamageInput;
    private javax.swing.JFormattedTextField jEscudoPersonaje;
    private javax.swing.JComboBox<String> jFortaleza;
    private javax.swing.JTextArea jJugadoresTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jListaPersonajes;
    private javax.swing.JTextField jNombreInput;
    private javax.swing.JTextField jNombreJugador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField jPrecision;
    private javax.swing.JLabel jRestantesTittle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField jVidaPersonaje;
    // End of variables declaration//GEN-END:variables
}
