
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author godoy
 */
public class Login_Apex extends javax.swing.JFrame {

    static ApexLegends a = new ApexLegends();

    /**
     * Creates new form ApexLegend
     */
    public Login_Apex() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        jLoginTitle = new javax.swing.JLabel();
        jUsername_title = new javax.swing.JLabel();
        jUserInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordInput = new javax.swing.JTextField();
        jIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setForeground(new java.awt.Color(255, 255, 255));

        jLoginTitle.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLoginTitle.setText("LOGIN");

        jUsername_title.setText("Usuario");

        jUserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Contraseña");

        jIngresar.setText("Ingresar");
        jIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIngresarMouseClicked(evt);
            }
        });
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFondoLayout = new javax.swing.GroupLayout(jFondo);
        jFondo.setLayout(jFondoLayout);
        jFondoLayout.setHorizontalGroup(
            jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFondoLayout.createSequentialGroup()
                .addGroup(jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsername_title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFondoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jFondoLayout.setVerticalGroup(
            jFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLoginTitle)
                .addGap(18, 18, 18)
                .addComponent(jUsername_title)
                .addGap(18, 18, 18)
                .addComponent(jUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIngresar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserInputActionPerformed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarActionPerformed

    private void jIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIngresarMouseClicked

        DefaultComboBoxModel lista = a.getListaJugadores();
        Random rnd = new Random();
        String nombre = jUserInput.getText();
        String password = jPasswordInput.getText();
        try {
            if (((Jugadores)lista.getElementAt(0)).getNombreUsuario().equalsIgnoreCase(nombre) &&((Jugadores)lista.getElementAt(0)).getPassword().equalsIgnoreCase(password) ||
                  ((Jugadores)lista.getElementAt(1)).getNombreUsuario().equalsIgnoreCase(nombre) &&((Jugadores)lista.getElementAt(1)).getPassword().equalsIgnoreCase(password)||
                    ((Jugadores)lista.getElementAt(2)).getNombreUsuario().equalsIgnoreCase(nombre) &&((Jugadores)lista.getElementAt(2)).getPassword().equalsIgnoreCase(password) ) {
                JOptionPane.showConfirmDialog(this, "Bienvenido");
                a.setVisible(true);
            } else {
                lista.addElement(new Jugadores(nombre, idGenerator(), password,a.darPersonaje()));
                JOptionPane.showConfirmDialog(this, "Bienvenido nuevo usuario");
                a.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
        

    }//GEN-LAST:event_jIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Apex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Apex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Apex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Apex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Apex().setVisible(true);

            }
        });
    }

    public static int idGenerator() {
        Random rnd = new Random();
        int id = rnd.nextInt(1000);
        boolean centinela = false;
        while (centinela == true) {
            int cont = 0;
            DefaultComboBoxModel lista = a.getListaJugadores();
            for (int i = 0; i < lista.getSize(); i++) {
                if (lista.getElementAt(i) instanceof Jugadores) {
                    if (((Jugadores) lista.getElementAt(i)).getID() == id) {
                        cont++;
                    }
                }
            }
            if (cont > 0) {
                id = rnd.nextInt();
            } else {
                centinela = true;
            }
        }
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jFondo;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLoginTitle;
    private javax.swing.JTextField jPasswordInput;
    private javax.swing.JTextField jUserInput;
    private javax.swing.JLabel jUsername_title;
    // End of variables declaration//GEN-END:variables

}
